### ISSUE TITLE
去广告不能运行

### ISSUE THREAD

**Issue by skyofstarry** [YYiiEt/Actions-OpenWrt-RaspberryPi4#4]
大佬，我编译了的固件，之后又在.config文件中加入了，adbyby plus功能，但是无法运行，在网上找了很多方法都不行，您能修复一下吗，还有可以加入一下些具有ap模式的无线网卡的驱动支持吗?

**Comment by YYiiEt** [comment]
l大说是64位系统无法运行......算不上是大佬，所以在这方面无能为力。其实adg去广告效果也还行，如果是刚需的话可以刷32位的树莓派2b固件。
usb网卡的话，由于每个人的所使用的都不一样，某些网卡会存在冲突，所以还是建议自己添加：
CONFIG_PACKAGE_kmod-usb-net-xxx（网卡型号添加）

**Comment by skyofstarry** [comment]
这里面也包含无线网卡吗？




| |
sunflower092030
|
|
邮箱：sunflower092030@163.com
|

Signature is customized by Netease Mail Master

在2020年03月19日 08:57，YYiiEt 写道：

l大说是64位系统无法运行......算不上是大佬，所以在这方面无能为力。其实adg去广告效果也还行，如果是刚需的话可以刷32位的树莓派2b固件。
usb网卡的话，由于每个人的所使用的都不一样，某些网卡会存在冲突，所以还是建议自己添加：
CONFIG_PACKAGE_kmod-usb-net-xxx（网卡型号添加）

**Comment by skyofstarry** [comment]
kmod-usb-net-xxx，好像是有限网卡的型号，哪些是无线网卡的驱动？

**Comment by YYiiEt** [comment]
emmm,取决于你自己使用的无线网卡型号。可以去找找openwrt有没有对应的驱动，如果没有就没有办法了，而且openwrt对无线网卡的支持很不好，还是搭配ap使用吧
